### ISSUE TITLE
使用idea打开项目会报mapping的xml找不到的错误

### ISSUE THREAD

**Issue by GavinAndre** [suxiongwei/springboot-rabbitmq#1]
具体错误如下
>java.io.FileNotFoundException: class path resource [com/sxw/springbootproducer/mapping/] cannot be resolved to URL because it does not exist

在pom文件的<build>标签内添加如下代码后可正常运行

```xml
        <resources>
            <!--编译之后包含xml-->
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>
```

**Comment by suxiongwei** [comment]
🤝

**Comment by dailiuyang123** [comment]
报 xml找不到。
可在：springboot-produce.pom 文件内添加如下代码：
  
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.properties</include>
                    <include>**/*.xml</include>
                </includes>
                <filtering>false</filtering>
            </resource>
        </resources>
