### ISSUE TITLE
生成环境中，这种消息高可用的方案级别不够吧！

### ISSUE THREAD

**Issue by a870368162** [suxiongwei/springboot-rabbitmq#4]
消息发送到了Exchange， ACK则会返回true，如果Exchange在转发到队列的过程中失败，加上你并没有开启消息持久化，所以这个消息则丢失了，另外即使你开启了消息持久化，假设rabbitmq在把消息持久化到硬盘的时候rabbitmq宕机，消息同样会丢失，高并发的场景下根本无法保证消息的高可用

**Comment by suxiongwei** [comment]
https://mp.weixin.qq.com/s/AgZiiDpkVyGod_nB8DrUvw

**Comment by a870368162** [comment]
没有事务要求的话，这篇文章的方法可行，我们生产环境下的方案比这篇文章的要复杂很多！
